name: Build and deploy Python app to Azure Web App - Findo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Create and start virtual environment, install dependencies
      - name: Create and start virtual environment
        shell: powershell
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          pip install -r requirements.txt

      # Step 4: Create zip artifact for deployment
      - name: Create zip artifact for deployment
        shell: powershell
        run: Compress-Archive -Path * -DestinationPath release.zip -Force

      # Step 5: Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Debug Secret Presence
      - name: Debug Secret Presence
        shell: powershell
        run: |
          if ("${{ secrets.AZURE_CREDENTIALS }}" -eq "") {
            Write-Output "Error: AZURE_CREDENTIALS secret is not set or empty"
            exit 1
          } else {
            Write-Output "AZURE_CREDENTIALS secret is set"
          }

      # Step 3: Login to Azure using Service Principal creds
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Findo'
          slot-name: 'Production'
          package: release.zip

      # Step 5: Post Azure Login
      - name: Post Azure Login
        if: always()
        run: echo "Post Azure Login step"
