name: Build and deploy Python app to Azure Web App - Findo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Create and start virtual environment
      - name: Create and start virtual environment
        shell: powershell
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1

      # Step 4: Install dependencies
      - name: Install dependencies
        shell: powershell
        run: pip install -r requirements.txt

      # Step 5: Create zip artifact for deployment
      - name: Create zip artifact for deployment
        shell: powershell
        run: Compress-Archive -Path * -DestinationPath release.zip -Force

      # Step 6: Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for Azure login via OIDC

    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip artifact using PowerShell
      - name: Unzip artifact for deployment
        shell: powershell
        run: Expand-Archive -Path release.zip -DestinationPath . -Force

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FOR_FINDO }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FOR_FINDO }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FOR_FINDO }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Findo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.MY_SECRECT_2 }}
          package: .
