name: Build and deploy Python app to Azure Web App - Findo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Create and start virtual environment, install dependencies
      - name: Create and start virtual environment
        shell: bash
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Create zip artifact for deployment
      - name: Create zip artifact for deployment
        shell: bash
        run: |
          mkdir -p app
          cp -r *.py requirements.txt app/
          cd app
          zip -r ../release.zip .
        working-directory: .

      # Step 5: Upload artifact for deployment jobs
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: https://Findo.azurewebsites.net

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Debug Azure Login Action Availability
      - name: Check Azure Login Action
        shell: bash
        run: |
          echo "Attempting to use azure/login@v3"
          curl -s -I https://github.com/azure/login/releases/tag/v3 | grep "HTTP/"
        continue-on-error: true

      # Step 3: Login to Azure using Service Principal creds
      - name: Azure Login
        uses: azure/login@v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Findo'
          slot-name: 'Production'
          package: release.zip
